# Exercise 1


Inspecting a Array NumPy

A numpy object has attributes and methods inherited from the class (numpy.ndarray). Creat an array and inspect the following attributes:



Shape: A tuple containing a number of elements (size) in each dimension of the array;

Size: Total number of elements in the array;

ndim: Number of dimensions (axes);

nbytes: Number of bytes used to store the data;

dtype: The data type of the elements in the array;



Implementation example:

import numpy as np
array = np.array([1, 2, 3, 4])
print('Shape: ', array.shape)

In [8]:
import numpy as np
array = np.array([1, 2, 3, 4])
print('Shape: ', array.shape)
print('Size:',array.size)
print('Ndim:',array.ndim)
print('Nbytes:',array.nbytes)
print('DType:',array.dtype)

Shape:  (4,)
Size: 4
Ndim: 1
Nbytes: 16
DType: int32


# Exercise 2


Based on the previous exercise, create a function that can receive an array and shows on the screen its attributes. Check if the insert argument is, indeed, a numpy object. You can also use a built-in type () function to verify the object' class.



Expected return:

inspect_array(np.array([1,2,3])) 
 
Shape : (3,)
Size:  3
Ndim:  1
Nbytes:  24
Dtype:  int64
Type:  <class 'numpy.ndarray'>
array([1, 2, 3])


inspect_array([1,2,3]) 
'The inserted object is not a NumPy array.'


In [15]:
def inspect_array(arr):
    if isinstance(arr,np.ndarray):
        print('Shape:',arr.shape)
        print('Size:',arr.size)
        print('NDIM:',arr.ndim)
        print('DTYPES:',arr.dtype)
        print('TYPE:',type(arr))
    else:
        print('The inserted object is not a NumPy array.')
              
        

In [16]:
inspect_array(array)

Shape: (4,)
Size: 4
NDIM: 1
DTYPES: int32
TYPE: <class 'numpy.ndarray'>


In [17]:
inspect_array([1,2,3])

The inserted object is not a NumPy array.


# Exercise 3

Use the np.array() function to creat the one-dimensioned arrays listed below:
a) Use a list as an argument and obtain:
array([-1,  4,  7,  9])
b) Use the range() function and obtain:
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Use a tuple as an argument and obtain:
array([10, 11, 12, 13, 14])
d) Use the range() function and obtain:
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])
e) Use the range() function and obtain:
array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920, 1910, 1900])
f) Obtain:
array(100)

In [18]:
np.array([-1,4,7,9])

array([-1,  4,  7,  9])

In [19]:
np.array(range(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.array(range(10,15))

array([10, 11, 12, 13, 14])

In [21]:
np.array(range(1990,2021,5))

array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [26]:
np.array(range(1900,2021,10))[::-1]

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

In [27]:
np.array([100])

array([100])

# Exercise 4


The np.ones() function allows you to create an array filled with the number 1 in all your entries. We can specify as arguments the shape and the kind of dtype of the array. Use this function to create the following arrays:





a) array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


b)



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])


c)



array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# A

In [33]:
np.ones((1,9)).ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

# B

In [35]:
np.ones((4,4)).reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# C

In [36]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Exercise 5


The np.zeros() function allows you to create an array filled with the number 0 in all your entries. We can specify as arguments the shape and the kind of dtype of the array (default is the float). Use this function to create the following arrays:

a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b)

array([[0., 0.],       
      [0., 0.]])  


c)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Exercise 6


Create the following arrays:



a)



array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])


b)



array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])


c)



array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])


Tip: use np.arange() or np.array(range()).

In [83]:
np.array(range(10,50,5)).reshape(8,-1)

array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [93]:
arr=np.array(range(50,4,-5))
np.negative(arr)

array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

In [95]:
np.array(range(50,150,2)).reshape(5,-1)

array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

# Exercise 7


Use the np.full(shape, fill_value, dtype) function to create the following arrays. This function allows you to create an array with a user-defined shape and dtype, filled with a certain value.

a)



array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


b)



array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])


c)



array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])


d)



array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])


Tip: Another possibility would be to obtain the arrays with a different operation, by mutiplying a matrix filled with the number 1 by a certain value.

In [99]:
np.full((10),5,dtype='float')

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [103]:
np.full((4,4),-5)

array([[-5, -5, -5, -5],
       [-5, -5, -5, -5],
       [-5, -5, -5, -5],
       [-5, -5, -5, -5]])

In [104]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [105]:
np.full((10,10),50)

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

# Exercise 8


Define the K array and check for missing data. Use the np.isnan() function.



array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])

In [111]:
arr=np.array([[ np.nan,   1.,  10.,   0.],
       [ np.nan,  np.nan,  np.nan,  np.nan],
       [100.,  50.,  np.nan, -25.],
       [ 30.,  np.nan,  np.nan, 130.]],order='K')
arr

array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])

In [113]:
np.isnan(arr).sum()

8

# Exercise 9


The np.linspace () function returns an array of evenly spaced numbers within a defined range. Create an array with numbers within the range [1,21] in 5 parts.



Expected return:

array([ 1.,  6., 11., 16., 21.])

In [115]:
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

# Exercise 10


The np.logspace () function returns evenly spaced numbers on a logarithmic scale. Create an array with numbers within the range [1,51] in 10 parts with the np.logspace() function.



Expected return:

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

In [117]:
np.logspace(1,51,10).reshape(-1,1)

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])